CREATE DATABASE PROMOTION_APPLICATION;
CREATE DATABASE ITEM_CATALOGUE;
CREATE DATABASE PRICING_APPLICATION;

GO

CREATE TABLE PROMOTION_APPLICATION..PA_ITEM (
    ITEM_ID INT NOT NULL PRIMARY KEY,
    ITEM_NAME VARCHAR(100) NOT NULL UNIQUE,
    ITEM_DESCRIPTION VARCHAR(1000) NOT NULL,
    BRAND_ID INT NOT NULL,
    BRAND_NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    PRICE_DATE DATE NULL,
    PRICE_VALUE FLOAT NULL
);

CREATE TABLE ITEM_CATALOGUE..IC_CATEGORY (
    CATEGORY_ID INT NOT NULL PRIMARY KEY,
    CATEGORY_NAME VARCHAR (100) NOT NULL UNIQUE,
    CATEGORY_DESC VARCHAR (1000)
);

CREATE TABLE ITEM_CATALOGUE..IC_BRAND (
	BRAND_ID INT NOT NULL PRIMARY KEY,
	BRAND_NAME VARCHAR(100) NOT NULL UNIQUE,
	BRAND_DESC VARCHAR(1000)
);

CREATE TABLE ITEM_CATALOGUE..IC_ITEM (
	ITEM_ID INT NOT NULL PRIMARY KEY,
	ITEM_NAME VARCHAR(100) NOT NULL UNIQUE,
	ITEM_DESCRIPTION VARCHAR(1000) NOT NULL,
	BRAND_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL
);

CREATE TABLE PRICING_APPLICATION..PR_PRICE (
	ITEM_ID INT NOT NULL,
	PRICE_DATE DATE NOT NULL,
	PRICE_VALUE FLOAT NOT NULL,
	CONSTRAINT pk_PRICE PRIMARY KEY (ITEM_ID, PRICE_DATE)
);
