SET NOCOUNT ON;
DECLARE @RowCount INT

SET @RowCount = 1

BEGIN TRANSACTION

WHILE @RowCount < 10001

BEGIN

SELECT TOP 1 a.CATEGORY_ID, b.BRAND_ID
INTO #tempdb FROM ITEM_CATALOGUE..IC_CATEGORY a, ITEM_CATALOGUE..IC_BRAND b
ORDER BY NEWID();

	INSERT INTO ITEM_CATALOGUE..IC_ITEM
	(
	ITEM_ID,
	ITEM_NAME,
	ITEM_DESCRIPTION,
	BRAND_ID,
	CATEGORY_ID
	)
		(SELECT 10000 + @RowCount
		, CONCAT('ITEM_',@RowCount)
		, CONCAT('ITEM_DESC_',@RowCount)
		, BRAND_ID
		, CATEGORY_ID
		 FROM #tempdb
		 )

	SET @RowCount = @RowCount + 1

	DROP TABLE #tempdb

END

COMMIT
